import Link from 'next/link';
import { GetStaticProps } from 'next';
import { formatPageTitle } from '../agents/pageTypes';
import { db } from '../db/finalInfoDB';

type HomeProps = {
  links: { slug: string; pageType: string; competitorName: string; pageTitle: string }[];
};

export default function Home({ links }: HomeProps) {
  return (
    <main style={{ maxWidth: 960, margin: '0 auto', padding: '2rem 1.5rem' }}>
      <h1>SliqPay comparison pages</h1>
      <p style={{ color: '#52525b' }}>
        Programmatic SEO pages generated by the research agent pipeline.
      </p>
      {links.length === 0 ? (
        <p>No pages in database yet. Run the pipeline after seeding competitors.</p>
      ) : (
        <ul>
          {links.map((l) => (
            <li key={`${l.slug}-${l.pageType}`}>
              <Link href={`/compare/${l.slug}/${l.pageType}`}>
                {l.pageTitle}
              </Link>
            </li>
          ))}
        </ul>
      )}
    </main>
  );
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  if (!process.env.DATABASE_URL) {
    return { props: { links: [] }, revalidate: 60 };
  }

  try {
    const { rows } = await db.query<{
      slug: string;
      page_type: string;
      name: string;
    }>(`
      SELECT c.slug, pc.page_type, c.name
      FROM page_content pc
      JOIN competitors c ON c.id = pc.competitor_id
      ORDER BY c.name, pc.page_type
      LIMIT 500
    `);

    return {
      props: {
        links: rows.map((r) => ({
          slug: r.slug,
          pageType: r.page_type,
          competitorName: r.name,
          pageTitle: formatPageTitle(r.page_type, r.name),
        })),
      },
      revalidate: 3600,
    };
  } catch {
    return { props: { links: [] }, revalidate: 60 };
  }
};
