/** High-value paths to probe on every competitor site (SPA-safe discovery). */
export const COMMON_PROBE_PATHS = [
  '/',
  '/pricing',
  '/fees',
  '/rates',
  '/exchange-rates',
  '/transfer',
  '/send-money',
  '/international-transfers',
  '/remittance',
  '/features',
  '/how-it-works',
  '/about',
  '/about-us',
  '/company',
  '/security',
  '/trust',
  '/legal',
  '/regulation',
  '/faq',
  '/help',
  '/support',
  '/contact',
  '/business',
  '/personal',
  '/india',
  '/send-money-to-india',
  '/usd-to-inr',
];

export const EXCLUDED_PATH_PATTERNS = [
  '/blog/',
  '/news/',
  '/press/',
  '/careers/',
  '/career/',
  '/jobs/',
  '/login',
  '/sign-in',
  '/signup',
  '/register',
  '/app/',
  '/download',
];
